- name: app setup
  ansible.builtin.import:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs
  ansible.builtin.import:
    name: common
    tasks_from: nodejs.yaml

- name: service setup
  ansible.builtin.import:
    name: common
    tasks_from: service-setup.yaml